executable            = jobTemplate.sh
getenv                = True
should_transfer_files = YES

arguments             = $(ClusterId) $(ProcId) $(filename)
output                = output/output_$(ClusterId)_$(ProcId).out
error                 = error/error_$(ClusterId)_$(ProcId).err
log                   = log/log_$(ClusterId)_$(ProcId).log

+JobFlavour           = "espresso"

queue filename from QCDPt80To120_dataFileName_All.txt