executable            = jobTemplate.sh
getenv                = True
should_transfer_files = YES

arguments             = $(ClusterId) $(ProcId) $(filename)
output                = out/output_$(ClusterId)_$(ProcId).out
error                 = err/error_$(ClusterId)_$(ProcId).err
log                   = log/log_$(ClusterId)_$(ProcId).log

+JobFlavour           = "espresso"

queue filename from dataFileNames.txt